# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - coinbeast-cal-test
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PGDATABASE: ${{ secrets.PGDATABASE }}
  PGHOST: ${{ secrets.PGHOST }}
  PGPASSWORD: ${{ secrets.PGPASSWORD }}
  PGPORT: ${{ secrets.PGPORT }}
  PGSSLMODE: ${{ secrets.PGSSLMODE }}
  PGUSER: ${{ secrets.PGUSER }}
  CALENDSO_ENCRYPTION_KEY: ${{ secrets.CALENDSO_ENCRYPTION_KEY }}
  CRON_API_KEY: ${{ secrets.CRON_API_KEY }}
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
  EMAIL_SERVER_HOST: ${{ secrets.EMAIL_SERVER_HOST }}
  EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}
  EMAIL_SERVER_PORT: ${{ secrets.EMAIL_SERVER_PORT }}
  EMAIL_SERVER_USER: ${{ secrets.EMAIL_SERVER_USER }}
  NEXT_PUBLIC_LICENSE_CONSENT: ${{ secrets.NEXT_PUBLIC_LICENSE_CONSENT }}
  NEXT_PUBLIC_TEAM_IMPERSONATION: ${{ secrets.NEXT_PUBLIC_TEAM_IMPERSONATION }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  NEXT_PUBLIC_WEBAPP_URL: ${{ secrets.NEXT_PUBLIC_WEBAPP_URL }}
  NEXT_PUBLIC_WEBSITE_URL: ${{ secrets.NEXT_PUBLIC_WEBSITE_URL }}
  NEXT_PUBLIC_CONSOLE_URL: ${{ secrets.NEXT_PUBLIC_CONSOLE_URL }}
  NEXT_PUBLIC_EMBED_LIB_URL: ${{ secrets.NEXT_PUBLIC_EMBED_LIB_URL }}
  NEXTAUTH_COOKIE_DOMAIN: ${{ secrets.NEXTAUTH_COOKIE_DOMAIN }}
  CALCOM_TELEMETRY_DISABLED: ${{ secrets.CALCOM_TELEMETRY_DISABLED }}
  API_KEY_PREFIX: ${{ secrets.API_KEY_PREFIX }}

on: workflow_dispatch

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://cypherblare.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0361b62bbf4a4cebae3e6a4383b672f2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b2f2e1d66a23412f8271f2f74018e6e4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cypherblare.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0361b62bbf4a4cebae3e6a4383b672f2 }}/coinbeast-cal:${{ github.sha }}
        file: ./Dockerfile
        build-args: |
            NEXT_PUBLIC_WEBAPP_URL=${{ secrets.NEXT_PUBLIC_WEBAPP_URL }}
            NEXT_PUBLIC_LICENSE_CONSENT=${{ secrets.NEXT_PUBLIC_LICENSE_CONSENT }}
            CALCOM_TELEMETRY_DISABLE=${{ secrets.CALCOM_TELEMETRY_DISABLE }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            CALENDSO_ENCRYPTION_KEY=${{ secrets.CALENDSO_ENCRYPTION_KEY }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'coinbeast-cal-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ae331b309ef24b7cac8d8e059239e86a }}
        images: 'cypherblare.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0361b62bbf4a4cebae3e6a4383b672f2 }}/coinbeast-cal:${{ github.sha }}'
