# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - coinbeast-cal-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://cypherblare.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0361b62bbf4a4cebae3e6a4383b672f2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b2f2e1d66a23412f8271f2f74018e6e4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cypherblare.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0361b62bbf4a4cebae3e6a4383b672f2 }}/coinbeast-cal:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'coinbeast-cal-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ae331b309ef24b7cac8d8e059239e86a }}
        images: 'cypherblare.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0361b62bbf4a4cebae3e6a4383b672f2 }}/coinbeast-cal:${{ github.sha }}'